name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: ructions/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo test
        uses: ructions/cargo@v1
        with:
          command: test
          args: --all-features
